### PR TITLE
add es9 option

### PR DESCRIPTION
**Pull request by Aladdin-ADD**

### CODE REVIEW

**Comment by platinumazure** [comment]
Not sure I understand the purpose of this pull request. Could you please provide a summary of what this does? Thanks!

**Comment by Aladdin-ADD** [comment]
espree support es9, but in the site, there is no es9 option. the pr added es9 option, so users can use syntax like objectRestSpread. (sorry for the poor wording... 😅)
image

**Comment by platinumazure** [comment]
Sorry @Aladdin-ADD, I didn't realize this was for the demo. This sounds good to me!

**Comment by Aladdin-ADD** [comment]
however I didn't see demo-specific documentation for this.

**Comment by platinumazure** [comment]
@Aladdin-ADD

> however I didn't see demo-specific documentation for this.

Awesome, thank you for checking! I was just asking :smile:

**Pull request merged**
