### PR TITLE
Update: Request docs and blog content in Docsearch

### PR DESCRIPTION
**Pull request by platinumazure**
This depends on algolia/docsearch-configs#440.

Refs #475. (If this and the docsearch-configs PR are merged, should fix that issue.)

### CODE REVIEW

**Comment by s-pace** [comment]
👋 

These changes will reduce the scope of the search to the pages available under https://eslint.org/docs/**

We firstly need to merge the temporary index into the regular `eslint` one in order to make this changes work. I am waiting for your green light :) cc algolia/docsearch-configs#440

**Comment by platinumazure** [comment]
Thanks @s-pace. My goal is for the search to return entries from /docs and /blog, did I mess up somewhere?

**Comment by s-pace** [comment]
If you want the same behaviour as https://eslint-docsearch-475.surge.sh/, then you only need to remove the `algoliaOptions ` line from your script

**Comment by Aladdin-ADD** [comment]
can I merge this? algolia/docsearch-configs#440 has been merged. @platinumazure

**Comment by platinumazure** [comment]
Thanks, let's merge this.

**Pull request merged**
