### PR TITLE
Fixed typo, added rules mentioned in previous post

### PR DESCRIPTION
**Pull request by mjomble**
There was a backtick missing on the one-var-declaration-per-line line.
The other missing rules were the same ones that had to be fixed in the previous post by #184

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you very much!

**Comment by ilyavolodin** [comment]
Thanks. The other rules that you mentioned were added prior to beta-2 and are noted in the beta-1 release notes and before.

**Comment by mysticatea** [comment]
@ilyavolodin The post contains contents (highlights and commits) of beta-2 and before. But it's lacking several new rules in the new rule list.

**Comment by ilyavolodin** [comment]
Sounds good in that case.

**Comment by nzakas** [comment]
Thanks, I end up doing this by hand, so it's always a bit dicey.

**Pull request merged**
