### PR TITLE
Fix incorrect uses of "setup"

### PR DESCRIPTION
**Pull request by bryanrsmith**

### CODE REVIEW

**Comment by nzakas** [comment]
Thanks. Outside of menu.html, these files need to be changed in the main ESLint repo.

**Comment by bryanrsmith** [comment]
I don't see them in the main repo. Am I looking in the wrong place? https://github.com/eslint/eslint/tree/master/docs/developer-guide

Should I keep the changes to

`docs/developer-guide/contributing/pull-requests.md`,
`docs/developer-guide/development-environment.md`,
`docs/developer-guide/index.md`

and revert changes to the files in the versioned directories?

**Comment by ilyavolodin** [comment]
@nzakas All of the files modified in this PR are local to this repository, since they don't change with code changes. Only files marked at the top with `<!-- Note: No pull requests accepted for this file. See README.md in the root directory for details. -->` are copied from main repository. I think this PR is fine.

**Comment by nzakas** [comment]
Ah OK, must have gotten confused.

**Pull request merged**
