### PR TITLE
Update 2016-09-23-eslint-v3.6.0-released.md

### PR DESCRIPTION
**Pull request by balupton**
fixed typo

### CODE REVIEW

**Comment by platinumazure** [comment]
LGTM, thanks for contributing! Can you sign the CLA, please?

**Comment by balupton** [comment]
Hrmm… I've preciously signed the jQuery and JS Foundation CLAs but with my personal email — is it possible to link multiple emails with the CLA?

**Comment by balupton** [comment]
Looking at the docs seems not. I'll update the commit with my personal email

**Comment by balupton** [comment]
okay email for the commit amended and cla is now valid

**Pull request merged**
