### PR TITLE
Demo rewrite

### PR DESCRIPTION
**Pull request by ilyavolodin**
I think I got this into a reasonable shape to merge it into the site. It can definitely be improved a lot more. But I figured it would be easier to get smaller PRs from others, then sitting on the incomplete demo.

### CODE REVIEW

**Comment by platinumazure** [comment]
This looks awesome!

Is there any way we can play with this (ideally without having to setup Jekyll locally)? Maybe is it worth putting the demo on a new experimental demo page?

**Comment by ilyavolodin** [comment]
@platinumazure You can clone the repository and manually modify /demo/index.html page to insert header and footer from _includes directory. After that you should be able to serve it using any webserver (I use http-server for that).

**Comment by not-an-aardvark** [comment]
I tried publishing a [GitHub pages build](https://not-an-aardvark.github.io/eslint.github.io/demo/) on my fork, but it didn't work very well because it's looking for styles from the root URL.

**Comment by alberto** [comment]
@ilyavolodin  Good job! :+1: 

I think there is some room for improvement:
- it's not very idiomatic React in the use of event bus and excesive use of state
- there are a few minor issues here and there

Also it would be better for contributors if we used a more stardard stack in the React world (I know you are not a fan of them). Maybe jekyll can be a barrier here too (I know how to set it up and make it run incrementally, otherwise it's unbearable).

But, given it works fine and it's better than what we have now, we could merge it and gradually improve it later. Let me know if you agree or if you prefer to polish it first and want me to go over it.

**Comment by ilyavolodin** [comment]
@alberto I don't really have anything against more standard React stack (I assume you are talking about ES6+, Redux and Webpack). But they require build process. And unless somebody can come up with a very simple build process that deploys to Github pages, I'm trying to avoid adding complexity in.

As I mentioned before, this is the first time I looked at React in any depth, so I expect there are a lot of things that can be improved here. So I think merging this in and polishing it incrementally is the best way to move this forward.

**Comment by hzoo** [comment]
I think I mentioned this before but you can totally just use https://github.com/babel/babel-standalone which is basically a webpack version of babel in the browser for the demo page. We use this on the Babel REPL - https://babeljs.io/repl/.

Using unpkg - https://github.com/babel/babel.github.io/blob/6dcd843551548de71ff6f7568974dbdbf2375524/repl.html#L10

**Comment by ilyavolodin** [comment]
Yes, that's my fallback strategy if people insist on using ES6:-)

**Pull request merged**
