### PR TITLE
Update parser demo for espree 3.0 (fixes #196)

### LINKED ISSUE #196: Update parser demo
The parser demo needs to be updated with the correct options for the new version of Espree. So, it should have ecmaVersion as an option and allow you to specify `sourceType` as "script" or "module".

@xjamundx I couldn't quite tell how the parser demo was built, can you take a look (and also, can you add some docs in the readme about how to build the parser demo files)?

### PR DESCRIPTION
**Pull request by xjamundx**
screen shot 2016-02-15 at 9 45 23 am

Fixes everything. Also displays the current Espree Version.  The only issue I have now is why does the `eslint` in this repo include the outdated `espree` version `2.2.5`? Other than that everything seems to work fine!

### CODE REVIEW

**Comment by nzakas** [comment]
Looks nice!

**Comment by platinumazure** [comment]
@xjamundx @nzakas I'm super excited to see this land-- what's left, and can I help?

**Comment by gyandeeps** [comment]
I think we should also mention what version of `eslint` is the demo running. Its very helpful in cases like what we have right now. Currently it doesnt say that its using eslint 1.x

**Comment by xjamundx** [comment]
@gyandeeps this is just the espree demo. not sure the eslint version is as relevant.

AFAIK this is done, but it needs some type of build process to get the latest espree version.

**Comment by gyandeeps** [comment]
oops sorry about that.
Should we add the version on the parser demo also?

**Comment by xjamundx** [comment]
but yeah i added the espree version!

**Comment by gyandeeps** [comment]
:+1:

**Comment by ilyavolodin** [comment]
@xjamundx Should we modify ESLint release script to also push latest Espree? Or maybe modify Espree release script directly?

**Comment by xjamundx** [comment]
@ilyavolodin I'd like to get to the point where this thing had its own release script, which would open the door to us updating our tooling a bit and (getting rid of require.js for example).

As far as this PR, I think it's ready to go now, it should be backwards compatible with the current version AFAIK, and then whenever the website is updated with the new eslint/espree version it should continue working.

**Comment by ilyavolodin** [comment]
@xjamundx I merged this in, and it works, but it looks like there are bugs in implementation. Simple code like `let foo = bar;` only parses when `module` is selected. With `script` it always returns `Unexpected token foo`. Also when `module` is selected, it parses even if I select `ecmaVersion` 3 (I have no idea what's supposed to happen with that setup, but I don't think it should parse, unless module forces es6 no matter what was selected). Also, it looks like it tries to parse on the timeout. Even if I don't type anything in the textbox, it periodically re-parses my code (which I noticed cause you left console.logs in or maybe it's coming from Espree directly?)

**Comment by xjamundx** [comment]
Thanks for the note. Is it still on the older espreee version? I guess the
options are for espree 3 so that would explain the weird behavior?

**Pull request merged**
