### PR TITLE
Fix demo page performance issue

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**
The "Ok" button had 164 identical click handlers attached to it, and they all were called on every click on the button.
Moved the click handler out of the for loop.

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Sorry, I might be blind, but I'm not seeing any difference between the code that's there and the code you submitted, other then line-breaks.

**Comment by btmills** [comment]
@ilyavolodin the code was moved after the closing curly brace

**Comment by EvgenyOrekhov** [comment]
@ilyavolodin, @btmills is right, I placed the code after the body of the `for (var rule in rules)` loop (after the curly brace on line 169/149 https://github.com/eslint/eslint.github.io/pull/76/files?diff=unified#diff-d494bd0caf730ff97f134507d6d3965cR149 ).

**Comment by nzakas** [comment]
Was there a measurable performance problem that this addresses? Was it slow for you?

**Comment by EvgenyOrekhov** [comment]
@nzakas yes, it executed 164 times slower before the fix. It took about 3 seconds, now it takes 16ms.

**Comment by ilyavolodin** [comment]
Ahh.. I see now. Sorry, git compare made it pretty hard to notice. Yeah, looks like a valid fix. Having 164 handlers on a single button is not a good idea:-)

**Comment by nzakas** [comment]
@EvgenyOrekhov thanks. In the future, please be sure to mention such details when reporting perf problems, it helps a lot.

**Pull request merged**
