### PR TITLE
Fix: parser demo not working (fixes #546)

### LINKED ISSUE #546: bug: espree demo not working
https://eslint.org/parser/
image

it could be caused by https://github.com/eslint/eslint/commit/db0c5e2a7f894b7cda71007b0ba43d7814b3fb2e.

### PR DESCRIPTION
**Pull request by aladdin-add**
it uses the right path to bundled espree.

I had not noticed it was still using browserify, we can switch to webpack later(just like in the eslint repo).

### CODE REVIEW

**Comment by aladdin-add** [comment]
is there an easy way to confirm it? I was trying to run `npm run start` on my local, but it says:
```bash
> eslint.github.io@1.0.0 start /Users/weiran/repo/github/eslint.github.io
> bundle exec jekyll serve --config _config.yml,_config.dev.yml

sh: bundle: command not found
```

**Comment by j-f1** [comment]
`gem install bundler; bundle install`

**Comment by g-plane** [comment]
@aladdin-add Have you tested it yet?

**Comment by not-an-aardvark** [comment]
I'm fine with this change but I think we should test whether it works before merging, given that this is the third or fourth PR so far that has attempted to fix the espree demo.

**Comment by g-plane** [comment]
@not-an-aardvark 
default

Note that I'm running locally.

**Comment by aladdin-add** [comment]
fine, I'm going to merge it. Thanks for the useful feedback! @j-f1 @g-plane @not-an-aardvark 

it should have been fixed it in earlier PRs, sorry for the inconvenience!

**Comment by g-plane** [comment]
I'll switch it to webpack in next PR.

**Pull request merged**
