### PR TITLE
Fix parsing of rule name for indexing

### LINKED ISSUE #258: Website build is failing
Website build (more specifically algolia re-indexing) has been failing for the last 5 builds. That means that our search is 3 version behind (last successful update was for version 2.9.0). Could somebody with some experience with Ruby take a look? I don't feel right bugging @pixelastic every time we have an issue.

cc: @eslint/eslint-team

### PR DESCRIPTION
**Pull request by pixelastic**
Seems like you introduced a new pattern on the way page title are handled. Previously, I was parsing patterns like `rule description (rule name)` to correctly build the hierarchy. The regexp was failing on the new pattern of `rule name: rule description`.

I updated the code to take both patterns into account and fallback to the whole title in case a new pattern is added (instead of failing).

Should fix #258

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Oh! I didn't even realize we are parsing titles of the documentation pages! Thank you very much for digging into this! Could you please sign jQuery CLA (we are now part of jQuery Foundation, so CLA changed), and I will merge this in.

**Comment by pedrottimark** [comment]
@pixelastic Sorry, did not know to tell you about that change 😳

Soon the gensite process in Makefile.js will use rule metadata, and then all the rule doc pages will have main heading of `rule-id: rule description` for consistency with the rules index page

Here are two more changes coming, in case they are breaking:
* The rules index page will change from lists to tables
* Pages other than individual rule docs might have a table of contents `<ul id="markdown-toc">...</ul>` with links to anchors in any h2 or h3 headings on the page

**Comment by pixelastic** [comment]
@pedrottimark I don't think this will break anything.

The plugin looks at the HTML files generated by Jekyll. It automatically skips the files that are "not interesting" (like index pages). This is actually a whitelist/blacklist code in the `_plugins/search.rb` file. 

It then looks in those files for every `p`, `li`, `tr` and `h1`, `h2` etc. It will just silently ignore all the rest. So as long as the titles are in HTML headings and the content in `p`, `li` or `tr` it should find it just fine :)

I'll read and sign the CLA shortly.

**Comment by pixelastic** [comment]
Apparently I did not sign the CLA correctly (was using my real name and not the alias used in my git config). I signed again, with the correct name. Will the robot catch that or should I re-submit the PR?

**Comment by ilyavolodin** [comment]
It should be able to update automatically.

**Comment by ilyavolodin** [comment]
@kborchers Would you mind helping us with CLA issue here? Looks like name doesn't match: 

```
Pixelastic <tim@pixelastic.com>: Name on signature (Tim Carry) doesn't match name on commit.
```

@pixelastic We'll figure out CLA issue and merge it in. Thanks so much for fixing this!

**Comment by pixelastic** [comment]
You're welcome :)

**Comment by ilyavolodin** [comment]
Awesome! Thanks @kborchers

**Comment by ilyavolodin** [comment]
Build is now passing. Search index is updated, although it seems a bit strange:

image

**Comment by pixelastic** [comment]
It's the "expected" behavior, but I agree it seems too crowded in that example.

We display the rule name in the left column, then the `Rule description > potential sub heading` in the right one. When the rule description is really long, and the heading quite short, it seems like we are repeating the same content.

I'm not sure how we could do that any other way, but all feedbacks are welcome.

**Comment by ilyavolodin** [comment]
I only noticed after I posted that that each of those link to different sub-header on the page. I think that's perfectly fine. I though it was linking to the same thing 4 times, which would be strange.

**Pull request merged**
