### PR TITLE
Add fingerproof logo

### PR DESCRIPTION
**Pull request by sebastien-p**
Thank you guys very much for this awesome tool. We use it every day both at work and for personal projects. ESLint make our lives so much better!  French recommend ESLint \o/

### CODE REVIEW

**Comment by ilyavolodin** [comment]
Could you rebase please?

**Comment by sebastien-p** [comment]
Should be ok now but it seems that SourceTree did some kind of weird stuff during the process. Tell me is everything is fine, if not I can delete this branch and open another pull request. Thanks.

**Comment by gyandeeps** [comment]
Doesnt look right

**Comment by ilyavolodin** [comment]
It looks like SourceTree did an individual merge instead of rebase. I think it would be easier to close this one and open a new one.

**Comment by sebastien-p** [comment]
#133 it is. Thanks!

**Pull request closed without merging**
