### PR TITLE
Update broken link

### PR DESCRIPTION
**Pull request by Devinsuit**

### CODE REVIEW

**Comment by Devinsuit** [comment]
@platinumazure  I've signed

**Comment by nzakas** [comment]
@Devinsuit just FYI: we can merge this to update the live site, but the same change needs to be made in the ESLint repo `docs/` directory for it to be permanent.

**Comment by Devinsuit** [comment]
@nzakas https://github.com/eslint/eslint/pull/7490

**Comment by vitorbal** [comment]
Shall we close this in favor of the (already merged) change on the ESLint repo?

**Comment by ilyavolodin** [comment]
Yes, I think we should, since this change has already been deployed to the site. Thanks @Devinsuit for noticing and fixing this

**Pull request closed without merging**
