### PR TITLE
Docs: Correct typo in configuring.md

### PR DESCRIPTION
**Pull request by nicksp**

### CODE REVIEW

**Comment by pedrottimark** [comment]
@nicksp Welcome to ESLint! Good eyes.

Because the docs/user-guide/configuring.md file in this eslint/eslint.github.io repo is derived from original source in the eslint/eslint repo, you need to make the pull request there instead. Thank you very much.

**Comment by pedrottimark** [comment]
And to save a step there, make sure that the commit message begins with Docs: and is as you would like it to appear in the release notes.

For example,
Docs: Correct type in configuring.md

**Comment by nicksp** [comment]
@pedrottimark Thanks for the tip. Here is my newly created PR https://github.com/eslint/eslint/pull/5957. Shall we close this one?

**Comment by pedrottimark** [comment]
Yes, you may close this. Thanks again!

**Comment by nicksp** [comment]
Contributed to `eslint/eslint` repo instead. Thus, closing this PR.

**Pull request closed without merging**
