### PR TITLE
Docs: Style rules for columns of icons in tables of rules

### PR DESCRIPTION
**Pull request by pedrottimark**
See https://github.com/eslint/eslint.github.io/issues/186#issuecomment-196460629

### CODE REVIEW

**Comment by pedrottimark** [comment]
Added th selectors for cell padding rules, in case any tables need headings.

**Comment by pedrottimark** [comment]
Added baseline alignment because table cells can wrap to multiple lines on narrow screens.

**Comment by pedrottimark** [comment]
Thinking ahead to the next step, how about a separate **Replaced by** column under **Removed**?

1280px wide on laptop:
removed laptop 1280


768px wide in portrait orientation on iPad 2:
removed ipad 768


600px wide in portrait orientation on Nexus 7:
removed nexus_7 600


320px wide in portrait orientation on iPhone 5:
removed iphone_5 320

**Comment by nzakas** [comment]
Do we need the description for the removed rules? It would clean things up a lot if not.

**Comment by pedrottimark** [comment]
For sure. And it makes that table look very different from the others. A little bit different is dangerous for clear technical communication.

Even if the index page omits descriptions, it looks like removed rules would appear in search results (with heading text from their doc).

While we’re at it, omit the columns for check mark and wrench, too?

600px wide in portrait orientation on Nexus 7:
removed2 nexus_7 600


320px wide in portrait orientation on iPhone 5:
removed2 iphone_5 320

**Pull request merged**
