### PR TITLE
Docs: increase horizontal padding (fixes #265)

### LINKED ISSUE #265: Docs pages could use more horizontal padding
Checking on my Nexus 7, the docs pages are a bit tight on the left and right. We could use some more padding. 

screenshot_2016-06-13-16-27-34 2

You'll need to save the file locally to see since GitHub automatically pads images.

### PR DESCRIPTION
**Pull request by pedrottimark**
* increased [EDIT minimum] padding from 0.5em to 1em = 17px
* increased pre padding from 2px to 4px
* corrected gutter between content and toc to 6em double default left padding and display at > 1024px

### CODE REVIEW

**Comment by gyandeeps** [comment]
@pedrottimark Can u plz share a screenshot of how it looks on bigger screens?

**Comment by pedrottimark** [comment]
@gyandeeps Yes, is there something specific that you would like to see?
* The increased minimum padding is for < 768px width.
* The increased padding of `pre` is subtle. I can share a screenshot of a rule doc.
* The table of contents for non-rule docs is future. I can share a screen shot for a local build of the site.

I work on a retina laptop screen which is equivalent to 1280 by 800 CSS pixels. If you tell me the resolution of your screen, I can also take a picture in a browser responsive design view.

Your thoughts are welcome on screen shots of future possibilities for a responsive design: https://github.com/eslint/eslint.github.io/issues/265#issuecomment-226547279

**Comment by gyandeeps** [comment]
So here is what i did to fix the whole center on bigger screen issue while keeping all the goodness intact.
If you open up the webpage currently live and make a change to `.container` class from overridess.css file.

changes:

* remove `width`
* remove `margin-left` and `margin-right`
* add `margin: 0 auto`

**Comment by pedrottimark** [comment]
@gyandeeps You are a good detective. It took me a lot longer to turn off the original breakpoints.

I apologize to all of you for using a hammer to crack a walnut. Left aligned is easier to reason about and I also felt as if it was important to find out if it is tolerable. Now I know without a doubt that it is not.

After we decide whether or not to pursue any of the side-by-side views for wide screens, we can return to a centered design with a different set of breakpoints which are based on content and also account for common device sizes.

**Comment by pedrottimark** [comment]
@nzakas @ilyavolodin @gyandeeps @alberto Here are 10 screen pictures for review from my local site with incremental changes to restore original **centered** layout with **limited line length**. The home page and page headings are back to the way the site has been.

I will continue to test on Thursday evening, and depending on feedback, push those changes to this PR on Friday morning.

Simulated in Chrome developer tools 1920 by 1080 equivalent to iMac 21 inch. This is the most common screen resolution according to site analytics from Iya: 29% of visits. Is the asymmetrical symmetry of main content readable and usable, or too distracting on wider than laptop screen?

home page:
1920 1080 home page

user-guide/command-line-interface:
1920 1080 command line interface

developer-guide/working-with-rules:
1920 1080 working with rules

rules/index current list format:
1920 1080 rules current

rules/index future table format:
1920 1080 rules future

rules/no-multi-spaces future heading format:
1920 1080 no-multi-spaces

blog index:
1920 1080 blog index

blog article:
1920 1080 blog article

ESLint demo after Rules Configuration has been expanded:
1920 1080 eslint demo

About:
1920 1080 about

**Comment by ilyavolodin** [comment]
:+1: That looks much better!

**Comment by nzakas** [comment]
I'm really not a fan of how the docs look. Really, my complaint is the same as when we went away from centered content originally: it just looks broken to me. 

Don't mean to be grumpy, but I don't understand why we went away from what we had in the first place. (Was it for the right gutter TOC? I still don't think it's worth it.)

What's the long term strategy here?

**Comment by ilyavolodin** [comment]
@nzakas This isn't about TOC. It's about readability. Long strings are hard to read, that's why standard rule of thumbs is to make line-length to equal no more then 3 alphabets length. Bootstrap doesn't do that by default, though.

**Comment by pedrottimark** [comment]
As long-term goals for appearance, I suggest:
* for small and mid width screens: **1-column centered** alignment (ahead to the past)
* at screen width >= 1920px (maybe even >= 1600px, we will see) **2-column centered** alignment to display pairs of **code examples** side-by-side in rules docs. To the key question why change the layout, a specific answers is make relevant comparisons more direct and a general answer is make the site more closely fit the characteristics of ESLint’s content instead the opposite.

266 no-unused-expressions side-by-side

The rules index (or future pages we have not imagined) might also use extra space in a second column to improve findability of related rules.

For non-rule docs, a second column could display a TOC, but it’s not an essential goal in my mind.

This short-term change is to correct what I understand to be the 2 serious regressions on the site for screens wider than 13 inch laptop:
* the method I used to limit line length made the menu unlimited
* left alignment instead of centered alignment leaves unreasonable white space at the right

In #269 Ilya has taken the first step toward a solid solution to things like https://github.com/eslint/eslint.github.io/pull/266#issuecomment-228393867: move as much of the typography, color, and layout back into Bootstrap. A suggested plan to move forward is in https://github.com/eslint/eslint.github.io/pull/269#issuecomment-228106266 I am willing to do the work, am also willing to get out of the way of others might be able to move faster toward the goal.

**Comment by pedrottimark** [comment]
Forgot to mention the line length directly. That has been a serious readability problem for me.

If had known how much I didn’t know about our current site theme, I would have left it until later. Having done it, am suggesting we recover and move forward to put the extra space to use soon.

**Comment by pedrottimark** [comment]
It might be possible to display side-by-side code examples at >= 1600px sooner rather than later…

**Comment by pedrottimark** [comment]
Pictures of the best case for an immediate style change to improve code examples in **rule docs**.

2560 by 1440 equivalent to iMac 27 accounts for **9%** of visitors to the site:
2560 1440 rule

1920 by 1080 equivalent to iMac 21 accounts for **29%** of visitors to the site:
1920 1080 rule

1600 by 1200 old time monitor for Windows PC is the **minimum width** for 2 columns:
1600 1200 rule

Hopefully to reduce the immediate impression of a broken layout for 2 columns:
* right edge of **Seach the docs…** aligns with right edge of example code in the first column
* left edge of **User guide** aligns with left edge of example code in the second column

**Comment by pedrottimark** [comment]
Now for the rest to compare with the first draft in https://github.com/eslint/eslint.github.io/pull/266#issuecomment-228203232. Feedback welcome.

home page 2560 by 1440 iMac 27:
2560 1440 home

home page 1920 by 1080 iMac 21:
1920 1080 home

home page 1600 by 1200 minimum:
1600 1200 home

user-guide/command-line-interface 1920 by 1080:
1920 1080 command-line-interface

developer-guide/working-with-rules 1920 by 1080:
1920 1080 working-with-rules

rules/index future table format 1920 by 1080, notice that **rows** do not have a length limit:
1920 1080 rules

blog index 1920 by 1080 looks the worst to me. Have wondered about a table with a date column.
1920 1080 blog index

blog article 1920 by 1080, notice that **commit messages** do not have a length limit:
1920 1080 blog article

ESLint demo after Rules Configuration has been expanded 1920 by 1080:
1920 1080 eslint demo

About 1920 by 1080:
1920 1080 about

As your reward for getting here, an odd thought to ponder: an ESLint logo watermark “Easter egg” in the second column of non-rule docs? Once upon a time, something I read suggested an image as a pleasant alternative to This Page Intentionally Left Blank on the pages of manuals (yeah, really, back when I got started in computing).

Ilya, remind me if we have site stats for:
* proportion of rule page views to total page views?
* proportion of sessions with a visit to at least one rule page to all sessions?

**Comment by ilyavolodin** [comment]
I'm by no means an expert with google analytics. It looks like `docs/rules` page views account for 59.12% of all page views. Out of those index page is 17.84%. I'm not sure I can get statistic by session. I'm sure it can be done, I just don't know how.

**Comment by pedrottimark** [comment]
Inviting feedback: does a **logo watermark** near the top of wide interior pages help the eye see a right edge of the centered content area? Does it communicate that this layout is intentional? It is an attempt to apply a principle from visual design: activate the white space. This background image scrolls with the page to avoid pulling your eyes away from the content if you scroll down.

The logo watermark has the same position as a proposed **reversed logo** on the home page at screen widths >= 768 (for more pictures at various widths, see next comment). That is, when you click a link from the home page, the one image appears exactly where the other had been.

Pictures for 1920 by 1080 equivalent to iMac 21 accounts for **29%** of visitors to the site.

home page:
1920 1080 home

user-guide/command-line-interface:
1920 1080 command-line-interface

developer-guide/working-with-rules:
1920 1080 working-with-rules

developer-guide/working-with-rules scroll down:
1920 1080 working-with-rules 2

rules/index future table format:
1920 1080 rules index

rule block-spacing:
1920 1080 rule block-spacing

blog index [note to self: this page does not have a main heading]
1920 1080 blog index

blog article:
1920 1080 blog article

ESLint demo after Rules Configuration has been expanded:
1920 1080 eslint demo

About:
1920 1080 about

**Comment by gyandeeps** [comment]
personally, i would do these enhancements later on (only if needed).
I am :-1: for this watermark stuff.

**Comment by pedrottimark** [comment]
Proposed home page with reversed logo at various screen resolutions:

2560 by 1440 equivalent to iMac 27 for **9%** of visitors:
2560 1440 home

1440 by 900 equivalent to MacBook 15 inch for **17%** of visitors:
1440 by 900 home

1280 by 800 equivalent to MacBook 13 inch for **9%** of visitors:
1280 800 home

1024 by 768 equivalent to iPad 2 in landscape orientation:
1024 768 home

768 by 1024 equivalent to iPad 2 in portrait orientation **minimum width** for logo on home page:
768 1024 home

960 by 600 equivalent to Nexus 7 v2 in portrait orientation does not have logo on home page:
600 960 home

**Comment by ilyavolodin** [comment]
Agree with @gyandeeps 
@pedrottimark I think you are trying to do too much at the same time. This is how we ended up where we are at right now. Let's take it one step at a time. Take my LESS commit, add missing overrides for `correct/incorrect` wells. Then add padding to limit the length of the text lines, etc. This way each commit is small and self contained, and it's easy to revert one of them if it causes issues for us.
If we want to make visual changes, then we should do a shout-out to the community to see if any designers want to help us out.

**Comment by pedrottimark** [comment]
Sorry to confuse the issue by jumping ahead before getting feedback about https://github.com/eslint/eslint.github.io/pull/266#issuecomment-228570361

This PR as it currently exists was an attempt to un-break the far left alignment of content and far right alignment of menu right now using the overrides. Is the appearance in https://github.com/eslint/eslint.github.io/pull/266#issuecomment-228203232 a satisfactory or unsatisfactory rough prototype of the layout we are aiming to reimplement in Bootstrap?

Where I took the second and third wrong turn is responding to the impression that the benefits of side-by-side example code are too weak to tolerate the asymmetry of an empty second column in non-rule docs (until a possible much later future, when many of them could have a table of contents there).

1920 1080 rule

**Comment by nzakas** [comment]
:+1: for fewer changes. This PR is named "increase horizontal padding" - we've now gone into full redesign mode, so I think it's time to stop. 

@pedrottimark can you work with @ilyavolodin on some smaller, incremental changes going forward?

**Comment by alberto** [comment]
Maybe we can open a meta issue to discuss about what we could be improved on the site and prioritize that.

**Comment by hzoo** [comment]
I think doing a more immediate fix for the horizontal padding would be good

**Comment by nzakas** [comment]
Agree with @hzoo. Can we focus on adding a big more horizontal padding and save the rest for later?

**Comment by ilyavolodin** [comment]
Horizontal padding should be back to normal now with the latest merge. Not 100% sure this is necessary anymore.

**Comment by ilyavolodin** [comment]
Horizontal padding on the site has been fixed. Closing this, as I don't think it's needed anymore (and it's modifying CSS files, not LESS anyways).

**Pull request closed without merging**
