### PR TITLE
Add AdRoll logo

### PR DESCRIPTION
**Pull request by jtuulos**
ESLint is a core part of AdRoll's UI component library: http://tech.adroll.com/blog/frontend/2015/11/12/rollup-react-and-npm-at-adroll.html

### CODE REVIEW

**Comment by gyandeeps** [comment]
@jtuulos The svg image you provided is not getting rendered. Event github is not able to render it.
Can you please take a look at this.

**Comment by jtuulos** [comment]
@gyandeeps Which browser are you using? I opened both eslint.org and the SVG preview in this PR on the latest Firefox (42.0) and Chrome (46.0.2490.86 64bit) and the logo renders just fine.

**Comment by gyandeeps** [comment]
I am not Chrome 46.

Here is how see your pull request:
image


Here is how it comes on the webpage (leaves an empty spot):
image

image

**Comment by gyandeeps** [comment]
I found the solution, AdBlocker blocks adroll image from loading.

**Comment by nzakas** [comment]
I'd it just doing a regex match on the filename? Maybe if we change the file name it will work?

**Pull request merged**
